### PR TITLE
Added topics on Error and Error Handling

### PR DESCRIPTION
**Pull request by araut1**
Added information about types of error and how to deal with them. Language and example are provided with beginner developers in mind.

Provided suitable example for compile-time error.

Let

### CODE REVIEW

**Comment by araut1** [comment]
Please check and let me know.

**Comment by annu12340** [comment]
Pls resolve the conflicts

**Comment by annu12340** [comment]
Hey @araut1 why do you close the pr
Are you facing any difficulty in resolving the conflict?

**Comment by annu12340** [comment]
You don't need to close an existing pr
Any time you make a change in  the file, it would be reflected in the pr
So you don't need to close and re-open the pr for each change

(This was a mistake that I myself made for a long time 😅 )

**Pull request closed without merging**
